{% set python_min = '3.11' %}
{% set name = "nionutils" %}
{% set version = "4.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fece020d804661cccb07721a88e70e6ac06c3709b0037822e7f2ce97be4e066e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nion.utils
    - nion.utils.test

about:
  home: https://github.com/nion-software/nionutils
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Nion utility classes.
  dev_url: https://github.com/nion-software/nionutils

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
