{% set name = "nionutils" %}
{% set version = "0.3.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f6096538e63d6e119c90bb4d530d3b323c264c4b5c29ca46e62ee298f6eaeea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - nion.utils
    - nion.utils.test

about:
  home: https://github.com/nion-software/nionutils
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Nion utility classes.
  dev_url: https://github.com/nion-software/nionutils

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
