{% set name = "nionutils" %}
{% set version = "0.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d6d0132a462f5bae4b7aa61e97f3c75801bda5871af684159ed3ee53f2bfe17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

test:
  imports:
    - nion.utils
    - nion.utils.test

about:
  home: https://github.com/nion-software/nionutils
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Nion utility classes.
  dev_url: https://github.com/nion-software/nionutils

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
